image: registry.meia8.com/john/node:8.7.0

stages:
- build
- deploy
- seelog

variables:
  CONTAINER_REGISTRY: registry.meia8.com
  CONTAINER_RELEASE_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  CONTAINER_RELEASE_IMAGE_TAG: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker tag $CONTAINER_RELEASE_IMAGE $CONTAINER_RELEASE_IMAGE_TAG
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE_TAG
  only:
  - tags
deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
    - kubectl delete -f deployment.yaml
    - kubectl create -f deployment.yaml
  when: manual
  environment:
    name: staging
    url: https://app-dev.qms888.com/qms-node
  only:
  - master
seelog-develop:
  stage: seelog
  script:
    - kubectl logs -f --limit-bytes=1000000 --since=5m $(kubectl get pods --namespace=development -l app=qms-node -o name) --namespace=development
  when: manual
  only:
  - master
seelog-test:
  stage: seelog
  script:
    - kubectl logs -f --limit-bytes=1000000 --since=5m $(kubectl get pods --namespace=test -l app=qms-node -o name) --namespace=test
  when: manual
  only:
  - master
